# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70708b943a03997441fa6fd76290b46661dcdbb69a35fc27ad82fe9751306c28e88adc981e9fbad3a3270c5cc1aea86991b1b7236ff22620686a5c914e90e645

test:
  secret_key_base: 5eaf09145f494a35905e28f695cc4c394969e2a03ab03fb08c8f33c5a4c0ace752e9c67399576e81939aa9d082276fcc94f4c221109e8d8a2b03b4a05fb72de3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
